### DISCUSSION TITLE
Grafana - adding user connection statistics?

### DISCUSSION THREAD

**Discussion by Vrtin** [mbugeia/srt2hls#14] [Ideas]
Hello,

Very nice docker combo indeed! :)

One question:
Is there a way to also see user connection statistics in Grafana dashboards?
I see the logs from Nginx are already there...

Like - number of concurent users, maybe even seperated for each hls quality + all combined?

Thanks & br, David

**Comment by mbugeia** [comment]
Hello David, this is an interesting question. 

I'm guessing what you want is a way to know how many listener are currently listening the HLS stream.
Unfortunately it's a little complicated to do. HLS isn't a connected protocol like Icecast. In Icecast the server know how many listener are connected and can give you the information. With HLS, the listener download playlist and segments but don't stay connected to nginx. Nginx can't know how many are listening the stream. 

To achieve this in HLS you can process nginx logs files in real time and aggregate them into prometheus metrics. This can be done either by 
- custom code that will process nginx logs and expose prometheus metrics
- using something like https://github.com/timberio/vector 

Vector pseudo-code 
```
sources:
  nginx_logs:
    type: file # or something else ?
    include:
    - /var/log/nginx/access.log 

transforms:
  remap: 
    type: remap
    inputs:
    - nginx_logs
    source: |
      # some remap code to parse nginx log
  metrics:
    type: log_to_metric
    inputs:
    - remap
    metrics:
    - type: counter
      field: duration # this should be the duration of the segment, parsed from the log line
      name: hls_listened_duration_total
      namespace: srt2hls
      increment_by_value: true
      tags:
        quality: "{{quality}}" # this should be the quality of the segment, parsed from the log line
sinks:
  prometheus:
    type: prometheus_exporter
    inputs:
    - metrics
    address: 0.0.0.0:9598
```
In this example you could use the metric `srt2hls_hls_listened_duration_total`
`sum(rate(srt2hls_hls_listened_duration_total[1m])) by (quality) # total concurrent listener by quality`
`sum(rate(srt2hls_hls_listened_duration_total[1m])) # total concurrent listener`

Another approach would be to code this into nginx with lua or C code. Or use another reverse proxy that can expose native prometheus metrics like this.

Keep in mind, theses stats will always be a estimate as different HLS client can have different behaviour (burst or linear download for example). 

Maxime
